name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Run a simple script
        run: |
          echo "This is a multi-line script"
          echo "Current directory: $(pwd)"
          ls -la
